image: gitpod/workspace-base

# bump trigger: 11
tasks:
  - init: |
      for i in $(seq 1 10); do echo $i; sleep 1; done;
      echo '3rd prebuild' > which.txt;
  - name: Short Script Task 🐇
    init: |
      for i in $(seq 1 20); do echo $i; sleep 1; done;
      sudo du -h / --max-depth=1 
    command: echo 'start script'
  - name: Long Script task
    init: |
      for i in $(seq 1 30); do echo $i; sleep 1; done;
      sudo du -h / --max-depth=1 
    command: echo 'start script'
